### PR TITLE
Time to Get Gassy

### PR DESCRIPTION
**Pull request by Fajetti**
## About The Pull Request

Allows the server to get incredibly gassy!

## Why It's Good For The Game

If you know, you know

## Changelog
:cl:
add: fart verb
/:cl:

### CODE REVIEW

**Comment by iknowdude00** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: 5ab0890d957d0ca30d3871ce56b4c35e8484b96a
Pull Request: 0e5d9e94f95efb24df7179fd3174a843677c31bf
Server: 860da58febb0631cab51cdd7d7cebad4a18b5b18

##### Comment
Why am I TMing this?
[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A%20Lumos Station 13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: dc80f2461ee994284a2157bad3b0f3a5015ed5ac
Pull Request: 0e5d9e94f95efb24df7179fd3174a843677c31bf
Server: 8c2b6c2874ead6071e10792ec671aaf52d805b7d

##### Comment
Why am I TMing this?
[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A%20Lumos Station 13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: e6beb4d593bac969432a3123da7390ddefc674ff
Pull Request: 0e5d9e94f95efb24df7179fd3174a843677c31bf
Server: 03665830c2dffa079975816c2abfa78157fbd284

##### Comment
Why am I TMing this?
[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A%20Lumos Station 13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: 4b33c2d44fb711d899b6b9b8b1dcf2b6b38d3be5
Pull Request: 0e5d9e94f95efb24df7179fd3174a843677c31bf
Server: 147814c01e68bf0fa36b884bcae1c5f6e64fbc69

##### Comment
Why am I TMing this?
[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A+Lumos+Station+13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Removed

**Comment by iknowdude00** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: e7e3f189cc44c6f39d2815f79a1abd920033ab17
Pull Request: d5bcf1a74f94af9fc82e1766354bf426f4f7c772
Server: 84768f2316af026771d6b2644db4acc8772418e4
[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A+Lumos+Station+13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: e7e3f189cc44c6f39d2815f79a1abd920033ab17
Pull Request: d5bcf1a74f94af9fc82e1766354bf426f4f7c772
Server: 51c4ba1c0ce587df063900aa8f5817b0fc10f87d

##### Comment

[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A+Lumos+Station+13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: 352b60912c5f535d3e524784125e8c76027c276b
Pull Request: d5bcf1a74f94af9fc82e1766354bf426f4f7c772
Server: f0a4765a3d86e3a41d76761060d56cca34370484

##### Comment

[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A+Lumos+Station+13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: ce8ce1cafc1837f889898412174e255506c0ef44
Pull Request: d5bcf1a74f94af9fc82e1766354bf426f4f7c772
Server: 1236607ee4c263aed1acfa7996dc317ed225f878

##### Comment

[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A+Lumos+Station+13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: 7ef745888bfa31dea0f51105c43a69d7b3f3f9b5
Pull Request: d5bcf1a74f94af9fc82e1766354bf426f4f7c772
Server: 4e6aba714aabe87df71cc466dd9d5b8bc6df65ec

##### Comment

[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A+Lumos+Station+13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Removed

**Comment by Fajetti** [comment]
I will not rest until my funny emote is MERGED

**Pull request closed without merging**
