### PR TITLE
Exorcising the code

### PR DESCRIPTION
**Pull request by KromeAngel**
## About The Pull Request

Removes the pride pin 2.0

## Why It's Good For The Game

Bashar al-Assad commanded me to do so.

## Changelog
del: Removed my comfort priderino pinerino
/:cl:

### CODE REVIEW

**Comment by Fajetti** [comment]
https://youtu.be/YgiyWGyJcIc

**Comment by iknowdude00** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: a92fa03ee9ea5f0ec0aa4b8699585a9f1605f6a7
Pull Request: 20a75327c6e097176cf91565c9d5d6884aba1ab6
Server: 03ab489ab98d55c361033618b7a163d06eb27668

##### Comment

[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A+Lumos+Station+13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: 67cfadaee8233fda5fe37f523ef9a6ff6cca7dd4
Pull Request: 20a75327c6e097176cf91565c9d5d6884aba1ab6
Server: c26630ead9c34a8625db4bba2874895611a7d1ee

##### Comment

[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A+Lumos+Station+13)
</details>

**Comment by iknowdude00** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
Lumos Station 13

##### Revision
Origin: 6d90afdd84ef72f7cd342052b847abafef6d1881
Pull Request: 20a75327c6e097176cf91565c9d5d6884aba1ab6
Server: bb3c1d359132e3dfd95dc671e5c1e11ac151ae93

##### Comment

[GitHub Deployments](https://github.com/Lumos-SS13/Lumos-3/deployments/activity_log?environment=TGS%3A+Lumos+Station+13)
</details>

**Pull request merged**
